stages:
  - check
  - build
  - test

include:
  - local: .gitlab/ci/*.gitlab-ci.yml

# Only allow `main` branch, tag pushing and merge request to execute pipeline
workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
