version: "3.8"
services:
  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data"
    command: ["--replSet", "dbrs", "--bind_ip_all"]
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 5s
      retries: 6
  server:
    build:
      context: ./server
    ###########################################################
    # Uncomment below lines to use Tensorflow with Nvidia GPU #
    ###########################################################
    #   dockerfile: Dockerfile.gpu
    # environment:
    #   NVIDIA_VISIBLE_DEVICES: all
    #   NVIDIA_DRIVER_CAPABILITIES: compute,utility
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - compute
    #             - utility
    command: make dev
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./server:/aifa
  grab_stock:
    build: ./grab_stock
    env_file:
      - grab_stock/.env
    depends_on:
      mongo: 
        condition: service_healthy
    volumes:
      - ./grab_stock:/grab_stock
volumes:
  mongo_data:
    driver: local
