# Template job for Kaniko image build
.kaniko-image-build-template:
  cache: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["sh"]

# Template job for python
# Requirement: define variable "AIFA_SUBDIRECTORY"
.python-template:
  image: python:3.10-slim
  variables:
    PIP_DEFAULT_TIMEOUT: "100"
    POETRY_INSTALLER_MAX_WORKERS: "4"
    POETRY_VERSION: "1.3.2"
  before_script:
    - export PIP_CACHE_DIR="$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY/.cache/pip"
    - export POETRY_CACHE_DIR="$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY/.cache/poetry"
    - apt-get update
    - apt-get install -y --no-install-recommends make
    - pip3 install "poetry==$POETRY_VERSION"
    - poetry config cache-dir "$POETRY_CACHE_DIR"
  after_script:
    - cd "$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY"
    - poetry env remove --all

# Template job for python lint
# Requirement: define variable "AIFA_SUBDIRECTORY"
.python-lint-template:
  extends:
    - .python-template
  after_script:
    - cd "$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY"
    - python3 "$CI_PROJECT_DIR/scripts/codequality_abs_path.py" $AIFA_SUBDIRECTORY gl-codequality.json
    - poetry env remove --all
