cron:lint:
  stage: check
  extends:
    - .mr-backend-job-rules
    - .python-lint-template
  variables:
    AIFA_SUBDIRECTORY: cron
  cache:
    key:
      files:
        - cron/poetry.lock
    paths:
      - cron/.cache/
  script:
    - cd "$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY"
    - make setup
    - make ci-lint
    - make format-check
  artifacts:
    when: always
    reports:
      codequality: cron/gl-codequality.json
# cron:build:
#   stage: build
#   extends:
#     - .kaniko-image-build-template
#     - .mr-job-skip
#   needs:
#     - server:lint
#   script:
#     - export AIFA_SERVER_DIR="${CI_PROJECT_DIR}/cron"
#     - export AIFA_IMAGE_NAME="${CI_REGISTRY_IMAGE}/cron"
#     - export AIFA_KANIKO_ARGS="--destination ${AIFA_IMAGE_NAME}:${CI_COMMIT_SHA}"
#     - |
#       if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
#         export AIFA_KANIKO_ARGS="${AIFA_KANIKO_ARGS} --destination ${AIFA_IMAGE_NAME}:latest";
#       elif [ -n "$CI_COMMIT_TAG" ]; then
#         export AIFA_KANIKO_ARGS="${AIFA_KANIKO_ARGS} --destination ${AIFA_IMAGE_NAME}:${CI_COMMIT_TAG}";
#       fi
#     - /kaniko/executor --cache --context "${AIFA_SERVER_DIR}" --dockerfile "${AIFA_SERVER_DIR}/Dockerfile" ${AIFA_KANIKO_ARGS}
