include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

container_scanning:
  variables:
    CS_DISABLE_LANGUAGE_VULNERABILITY_SCAN: "true"
    CS_DOCKERFILE_PATH: "$CI_PROJECT_DIR/server/Dockerfile"
    CS_IMAGE: "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_SHA"
