# Template job for Python project build
.server-python-template:
  image: python:3.10-slim
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/server/.cache/pip"
    POETRY_CACHE_DIR: "$CI_PROJECT_DIR/server/.cache/poetry"
    POETRY_HOME: /opt/poetry
  cache:
    key:
      files:
        - server/poetry.lock
    paths:
      - server/.cache/
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y curl make
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$POETRY_HOME/bin:$PATH"
  after_script:
    - export PATH="$POETRY_HOME/bin:$PATH"
    - cd server/
    - poetry env remove --all

.kaniko-image-build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ["sh"]
  cache:
    key:
      files:
        - server/Dockerfile
    paths:
      - /cache

server:lint:
  stage: check
  extends:
    - .server-python-template
  script:
    - cd server/
    - make setup
    - make lint
    - make format-check

server:build:
  stage: build
  extends:
    - .kaniko-image-build
    - .skip-merge-request
  needs:
    - server:lint
  script:
    - export AIFA_SERVER_DIR="${CI_PROJECT_DIR}/server"
    - export AIFA_IMAGE_NAME="${CI_REGISTRY_IMAGE}/server"
    - export AIFA_KANIKO_ARGS="--destination \"${AIFA_IMAGE_NAME}:CI_COMMIT_SHA\""
    - |
      if [ "$CI_COMMIT_BRANCH" = "$CI_DEFAULT_BRANCH" ]; then
        export AIFA_KANIKO_ARGS="${AIFA_KANIKO_ARGS} --destination \"${AIFA_IMAGE_NAME}:latest\"";
      elif [ -n "$CI_COMMIT_TAG" ]; then
        export AIFA_KANIKO_ARGS="${AIFA_KANIKO_ARGS} --destination \"${AIFA_IMAGE_NAME}:${CI_COMMIT_TAG}\"";
      fi
    - |
      /kaniko/executor
        --cache
        --cache-dir "/cache"
        --compressed-caching false
        --image "python:3.10-slim"
        --context "${AIFA_SERVER_DIR}"
        --dockerfile "${AIFA_SERVER_DIR}/Dockerfile"
        ${AIFA_KANIKO_ARGS}
