# Template job for NodeJS project build
.web-node-template:
  image: node:16-slim
  cache:
    key:
      files:
        - web/yarn.lock
    paths:
      - web/.yarn-cache/
  before_script:
    - yarn config set yarn-offline-mirror "$CI_PROJECT_DIR/web/.yarn-cache/" --global
    - yarn config set yarn-offline-mirror-pruning true --global

web:lint:
  stage: check
  extends:
    - .web-node-template
  script:
    - export ESLINT_CODE_QUALITY_REPORT="$CI_PROJECT_DIR/server/gl-codequality.json"
    - cd web/
    - yarn install --frozen-lockfile
    - yarn ci:lint
    - yarn format-check
  artifacts:
    when: always
    reports:
      codequality: server/gl-codequality.json

web:test:
  stage: check
  needs:
    - web:lint
  extends:
    - .web-node-template
  script:
    - cd web/
    - yarn install --frozen-lockfile
    - yarn ci:test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    reports:
      junit:
        - web/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: web/coverage/cobertura-coverage.xml

web:build:
  stage: build
  needs:
    - web:lint
    - web:test
  extends:
    - .skip-merge-request
    - .web-node-template
  script:
    - cd web/
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/web/build/"
