# Template job for NodeJS project build
.web-node-template:
  image: node:16-slim
  extends:
    - .node-template
  variables:
    AIFA_SUBDIRECTORY: web
  cache:
    key:
      files:
        - web/yarn.lock
    paths:
      - web/.yarn-cache/

web:lint:
  stage: check
  extends:
    - .mr-frontend-job-rules
    - .web-node-template
  script:
    - export ESLINT_CODE_QUALITY_REPORT="$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY/gl-codequality.json"
    - cd "$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY"
    - yarn install --frozen-lockfile
    - yarn ci:lint
    - yarn format-check
  artifacts:
    when: always
    reports:
      codequality: server/gl-codequality.json

web:test:
  stage: check
  needs:
    - web:lint
  extends:
    - .mr-frontend-job-rules
    - .web-node-template
  script:
    - cd "$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY"
    - yarn install --frozen-lockfile
    - yarn ci:test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    when: always
    reports:
      junit:
        - web/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: web/coverage/cobertura-coverage.xml

web:build:
  stage: build
  needs:
    - web:lint
    - web:test
  extends:
    - .mr-job-skip
    - .web-node-template
  script:
    - cd "$CI_PROJECT_DIR/$AIFA_SUBDIRECTORY"
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - web/build/
